### ISSUE TITLE
File structure

### ISSUE THREAD

**Issue by Feinminen** [mglkn/dummy-slider#10]
В проекте по слайдеру должно быть явное разделение на плагин и демо страницу. Сейчас всё лежит вместе и не совсем понятно где что :)
Также не совсем понятно разделение на dev/src. В папке config - лучше явно указать, что это конфиг вебпака, т.к. там могут быть и конфиги линтеров и прочей лабуды.

До тех пор, пока в проетке нет либ, которые навязывают динамический рендер через js.
Все статические элементы лучше рисовать обычным html (через pug в данном случае). Я к тому, что не совсем понятно зачем весь html аппендить в проект template строкой, на мой взягляд у такого подхода нет преимуществ, но есть существенные недостатки.
![image](https://user-images.githubusercontent.com/44312820/97800197-e4c01400-1c65-11eb-9e6a-cdf9a5edce69.png)

**Comment by mglkn** [comment]
webpack конфиги теперь в своей папке живут.

demo page из dev переехал в src и бы распилен на 2 компонента - SliderBlock  (иплементирует на странице конкретный слайдер и настройки) и DemoPage (сама демо страница с хидером).
