### ISSUE TITLE
Airbnb styleguide

### ISSUE THREAD

**Issue by Feinminen** [mglkn/dummy-slider#11]
По стандартам: 
![image](https://user-images.githubusercontent.com/44312820/97800370-50ef4780-1c67-11eb-80c7-d7532a9c3973.png)

Чтобы с этим не было проблем - можно установет пакет линта с правилами airbnb:
[тык](https://www.npmjs.com/package/eslint-config-airbnb-typescript)

**Comment by mglkn** [comment]
Вроде настроил.
