### ISSUE TITLE
Fixes from the previous project

### ISSUE THREAD

**Issue by Feinminen** [mglkn/dummy-slider#12]
Нужно пофиксить все недочеты, по которым я оставлял ишьюс в предыдущем проекте.

**Comment by mglkn** [comment]
Вроде порефакторил. Есть только один момент `SliderView.scss` я растаскивать по view компонентам не стал. horizontal/vertical позиционирование слайдера решается через модификатор `.slider_vertical`, который каскадом, внутри блока, задает нужные стили. Ну если это критично, то, распилю, конечно.
