### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by Feinminen** [mglkn/dummy-slider#13]
Необходимо настроить test coverage, для проверки покрытия функционала слайдера тестами.
И сейчас некоторые тесты пропускаются почему-то.
![image](https://user-images.githubusercontent.com/44312820/99479689-3d432100-2989-11eb-9479-f2b73cfde43e.png)

**Comment by mglkn** [comment]
3 теста skiped были потому, что я когда-то забыл снять с одного теста .only =) Модель я как-то серьезно не менял, и после снятия "эмбарго" (=)) не прошел только один тест из трех которых был написан исходя их некоторой логики валидации (сейчас она поменялась).

**Comment by Feinminen** [comment]
Желательно ещё мальца поднять процент покрытия кода тестами, особенно по веткам условных операторов. У coverage есть полный отчет, в котором можно явно смотерть где и какая ветка/функция не затестирована.

**Comment by mglkn** [comment]
![cover](https://user-images.githubusercontent.com/62555883/99813947-5d293f00-2b59-11eb-8781-c3d185605d7f.png)
