### ISSUE TITLE
Minor remarks

### ISSUE THREAD

**Issue by Feinminen** [mglkn/dummy-slider#17]
Поглядеть, чтобы нигде не было закоменченного кода.
![image](https://user-images.githubusercontent.com/44312820/99483081-13d9c380-2990-11eb-94b8-d7533d1fd17d.png)

В целом коментарии в самом коде - достаточно спорная штука, они нужны только при наличии какой-то нетривиальной логики. Имхо, лучше вынести какие-то моменты в доку. + у тебя где-то комментарии на русском, а где-то на английском, выглядит странновато слегка :)
![image](https://user-images.githubusercontent.com/44312820/99483189-4f748d80-2990-11eb-985e-155073d078fd.png)

**Comment by mglkn** [comment]
Там где не на русском - я для себя оставлял. А на русском - что-то типа документации для того кто читать будет, что бы легче было понять что к чему. Я все удалил что бы не смущали (они все равно дублировали README).
