### ISSUE TITLE
Баги и недочёты слайдера.

### ISSUE THREAD

**Issue by a-poluhin** [mglkn/dummy-slider#2]
Сделать возможность при клике на трэк бегунка изменять значение слайдера.
Сделать возможность выбора интервального/обычного слайдера в опциях.

Значения разных тултипов не могут быть одинаковыми и при одинаковых значениях не возможно передвинуть минимальное значение.
![image](https://user-images.githubusercontent.com/10168007/90749825-21829d00-e2fe-11ea-97e7-91c1782b9fee.png)

Исключить возможность слишком большого шага
![image](https://user-images.githubusercontent.com/10168007/90750135-981f9a80-e2fe-11ea-981e-1920912ff641.png)

Когда меняешь шаг - если шаг не удовлетворяет значениям слайдера, значение слайдера должно меняться мгновенно.

**Comment by mglkn** [comment]
Спасибо за issue.

Сделать возможность при клике на трэк бегунка изменять значение слайдера.
https://github.com/mglkn/dummy-slider/commit/fd4946855346160e77b34deb8015684674459dba

Сделать возможность выбора интервального/обычного слайдера в опциях.
Интервальный/обычный слайдер задается через value (value: [1] - обычный, value: [1,2] - интервальный). Я "допилил" что бы его можно было менять, и прикрутил к demo отдельным чекбоксом.
https://github.com/mglkn/dummy-slider/commit/cd70a757600b14e58083f757b09022f32e86d95a

Значения разных тултипов не могут быть одинаковыми и при одинаковых значениях не возможно передвинуть минимальное значение.
Если я правильно понял, то был такой баг: при слишком быстром движении мыши при равном значении "точек" из позиции не совпадали, я это пофиксил.
https://github.com/mglkn/dummy-slider/commit/52c4fdfe4c54bc86ee4d185264f3ad673362c419

Исключить возможность слишком большого шага
https://github.com/mglkn/dummy-slider/commit/5b9ff61d67f710276be28c750c340cb657c1149f

Когда меняешь шаг - если шаг не удовлетворяет значениям слайдера, значение слайдера должно меняться мгновенно.
Этого я не понял. Если значения не валидны - они не применяются к стейту.

**Comment by a-poluhin** [comment]
> Значения разных тултипов не могут быть одинаковыми и при одинаковых значениях не возможно передвинуть минимальное значение.
> Если я правильно понял, то был такой баг: при слишком быстром движении мыши при равном значении "точек" из позиции не совпадали, я это пофиксил.

Тут имелось ввиду что нужно исключить возможность одинакового значения для минимального максимального значения для интервалов.=)

Интервал отключен, но после выставления нового промежутка он включается.
![bug-toggle-range](https://user-images.githubusercontent.com/10168007/93424730-cc2cb200-f8e2-11ea-87e1-b7bf6378bc61.gif)

**Comment by mglkn** [comment]
Интервал отключен, но после выставления нового промежутка он включается.
Починил.
https://github.com/mglkn/dummy-slider/commit/d03ebadd622743467a6f86b8a45a0e166af116a8

Если я все правильно понял. Сделал так что значения range не могут быть одинаковыми (т.е. минимальный range всегда есть)

Передеплоил.
https://mglkn.github.io/slider/
