### ISSUE TITLE
Именование

### ISSUE THREAD

**Issue by a-poluhin** [mglkn/dummy-slider#3]
Если есть папка в которой лежат только классы, то она должна начинаться с большой буквы(Controller, View и т.д.)

**Comment by mglkn** [comment]
https://github.com/mglkn/dummy-slider/commit/f4f59ea7d631100d88e4af738fccc45d409ba47b

**Comment by a-poluhin** [comment]
> [f4f59ea](https://github.com/mglkn/dummy-slider/commit/f4f59ea7d631100d88e4af738fccc45d409ba47b)
Не изменил именование папок.
