### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by a-poluhin** [mglkn/dummy-slider#4]
Старайся не использовать as без крайней необходимости. Например тут as number не нужен ведь typescript уже знает что в step может лежать number. Единственное у тебя typescript так же показывает что значение step может быть undefined, но для того чтобы этой ошибки не было достаточно проверить наличие значения переменной step.
![image](https://user-images.githubusercontent.com/10168007/91294078-2f836280-e7c3-11ea-9b1d-f5f9882c537a.png)

Проверь во всех ли местах нужна проверка "someParam?".
![image](https://user-images.githubusercontent.com/10168007/91400529-02d65600-e86a-11ea-9f6e-8c1ed38583af.png)

У typescript можно определить публичные(public), приватные(private) методы и можно будет убрать у приватных методов в названии нижнее подчеркивание.
![image](https://user-images.githubusercontent.com/10168007/91410853-bb53c800-e871-11ea-9be0-150e670f4522.png)

**Comment by mglkn** [comment]
Спасибо за issue;

Удалил приведение типов там где, они заменяли проверку на undfined. В основном это поля options или state. Т. к. в конструкторе options явно задаются значения по умолчанию я сделал их строгими и удалил `as`. В местах взаимодействия с DOM (например получение размера блока возвращает number | undefined) явно проверяю на undefined. 

https://github.com/mglkn/dummy-slider/commit/6d6317c019231aca73e8265519644f2694b60f13

Переписал приватные методы.

https://github.com/mglkn/dummy-slider/commit/a55d70092789626bfe759e76157c6fa79677aa83
