### ISSUE TITLE
Конструкторы классов

### ISSUE THREAD

**Issue by a-poluhin** [mglkn/dummy-slider#5]
Конструкторы классов должны оставаться максимально легковесными и маленькими по объему.
Всё что нужно для инициализации можно перенести в отдельный метод 'init' и сразу вызывать его в конструкторе.
![image](https://user-images.githubusercontent.com/10168007/91300971-5bf0ac00-e7ce-11ea-87e0-2e6134f1b068.png)

**Comment by mglkn** [comment]
https://github.com/mglkn/dummy-slider/commit/1eccf2740d5247826c1b29721d27970bb3663f87
