### ISSUE TITLE
Деструктуризация

### ISSUE THREAD

**Issue by a-poluhin** [mglkn/dummy-slider#6]
Чтобы везде не писать this.state - можно деструктуризацию использовать. Надо везде чекнуть, чтобы данные с объектов доставались деструктуризацией.
![image](https://user-images.githubusercontent.com/10168007/91410693-7b8ce080-e871-11ea-86ab-1f44c8740d28.png)

**Comment by mglkn** [comment]
Спасибо за issue

https://github.com/mglkn/dummy-slider/commit/111ac482e9ad0cbfdd7615a293574ff5755768e1

**Comment by mglkn** [comment]
https://github.com/mglkn/dummy-slider/commit/ddddb185bfdc3a5dada297fefa9508281b2b9e0c
