### ISSUE TITLE
Привязка контекста

### ISSUE THREAD

**Issue by a-poluhin** [mglkn/dummy-slider#7]
Для того чтобы избежать постоянного добавления bind(this) - можно использовать class properties или bind декораторы, например autobind из core-decorators.
![image](https://user-images.githubusercontent.com/10168007/91413084-d247e980-e874-11ea-9cd0-f0767e8aa78e.png)

**Comment by mglkn** [comment]
Спасибо за issues!

Я прошу прощения за "лаг".
Уведомления о issues из css макета мне приходили на почту. Оказалось я был подписан на него при создании, а на этот репозиторий почему-то нет (я не знал как вся эта машинерия работает). Поэтому сюда не заглядывал, ожидая либо почтовых уведомлений или в "ленте" гитхаба, и как дурак писал в телегу "Жду issues". Извиняюсь.

https://github.com/mglkn/dummy-slider/commit/61f5d634aeb372358dd39957b81a8e4b10cabaa9
