### ISSUE TITLE
Ошибки при сборке

### ISSUE THREAD

**Issue by a-poluhin** [mglkn/dummy-slider#8]
Проверь ошибки сборки
![image](https://user-images.githubusercontent.com/10168007/93423289-d7321300-f8df-11ea-80de-8ce37a6eeba2.png)
Можешь попробовать клонировать с гитхаба проект и запустить его.

**Comment by mglkn** [comment]
git + windows + casesensitive = false кода ты рефакторишь переименовывая папки =)

https://github.com/mglkn/dummy-slider/commit/caad409803254b2197d37fdf5593a4e4b2d2a527
