### ISSUE TITLE
Slider functionality

### ISSUE THREAD

**Issue by Feinminen** [mglkn/dummy-slider#9]
1. Тултип тоже должен быть интерактивным, нужно добавить возможность менять значения слайдера перетягивая тултип, также как сейчас его можно менять за 'бегунок'. Так будет гораздо удобнее с точки зрения юзабилити, т.к. не придётся целится на маленький thumb, чтобы поменять значение.
Также, желательно сделать хоть какую-то обводку у тултипа, т.к. порой может показаться, что это кусок странно отобразившейся шкалы, имхо :)

2. Шаг слайдера должен влиять именно на то как передвигается слайдер, а не на то какие условно у слайдера могут быть занчения в опциях/тултипе (как при клике на шкалу). Чтобы было понятнее - прикрепил гифку с ожидаемым поведением (на гифке шаг 5000).
![sliderEx](https://user-images.githubusercontent.com/44312820/97799343-52694180-1c60-11eb-900f-aefbb3e2c710.gif)

3. Шкала должна подстраиваться под шаг. Причем, если в сладере маленький шаг, то количество элементов в шкале должно быть такое, чтобы элементы не колапсились друг с другом, если большой - то просто должны быть значения которые входят в шкалу (как на гифке выше).

4. Нужно сделать так, чтобы изменения настроек слайдера применялись мгновенно и сразу валидировались, без клика на апдейт. По факту - клик на апдейт - просто лишнее движение, даже если юзер захочет поменять и шаг и максимальное значение, то ничего страшного не случится, если изменения произойдут последовательно.

5. Сейчас связанный стейт приложения не всегда обновляется корректно:
![image](https://user-images.githubusercontent.com/44312820/97799894-2bf8d580-1c63-11eb-8e39-354e3e687a4d.png)
![image](https://user-images.githubusercontent.com/44312820/97799938-7da16000-1c63-11eb-8e9f-9f35ec69012c.png)

6. Порой у бегунка вообще очень странное поведение, он будтно застревает на каком-то моменте шкалы (ещё до граничного значения)
![stuck](https://user-images.githubusercontent.com/44312820/97799800-b1c85100-1c62-11eb-9179-b1cecb0c5c90.gif)

7. Основой хорошего приложение является его 'прочность'/стабильность - юзер ни при каких обстоятельствах не должен поломать слайдер, сейчас это сделать достаточно легко.

8. Валидация значений это круто, но, имхо, ей лучше не злоупотреблять и в тех моментах когда юзер делает какое-то действие, которое можно как-то достаточно явно инерпритировать - лучше это действите делать, меняя опции. 
Например, при включении рэйнжа, если первое значение больше второго(а ведь может быть вообще так, что сейчас такой диапазон, что физически не получится выставить значение меньше, чем было у второго бегунка) - то нужно включать рэйнж, изменяя какое-то из значений бегунков, но чтобы они были валидны по текущим опциям, соответсвенно.

**Comment by Feinminen** [comment]
При переключении шага - меняются значения в лэйбле, но не позиция бегунков слайдера:
![image](https://user-images.githubusercontent.com/44312820/99225019-f4208f00-2819-11eb-80ed-e7cb41001034.png)

При явно указывании значения через панель - валидируется всё, кроме позиции :)
![value](https://user-images.githubusercontent.com/44312820/99225160-2fbb5900-281a-11eb-8f68-e3f0d1dd9b93.gif)
И ещё порой при изменении значения одного бегунка почему-то меняются занчения другого.

Также ещё учтены не все кейсы, чтобы не происходило 'слияния' шкалы.
![image](https://user-images.githubusercontent.com/44312820/99225532-c851d900-281a-11eb-89e5-3bc74a74a83d.png)

**Comment by mglkn** [comment]
Вроде пофиксил.
